SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720
PLAYER_RADIUS = 20
LINE_WIDTH = 2
PLAYER_TURN_SPEED = 300
PLAYER_ACCELERATION = 400
PLAYER_DRAG = 120
PLAYER_BRAKE_STRENGTH = 500
PLAYER_MAX_SPEED = 300
PLAYER_STOP_EPSILON = 5
ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE_SECONDS = 0.8
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS
ASTEROID_NUM_VERTICES = 12
ASTEROID_LUMPINESS = 0.35
SHOT_RADIUS = 5
SHOT_LIFETIME = 2.5
PLAYER_SHOT_SPEED = 500
PLAYER_SHOOT_COOLDOWN_SECONDS = 0.3
SCORE_LARGE_ASTEROID = 20
SCORE_MEDIUM_ASTEROID = 50
SCORE_SMALL_ASTEROID = 100
PLAYER_STARTING_LIVES = 3
PLAYER_RESPAWN_INVULNERABLE_SECONDS = 2.0
HUD_FONT_SIZE = 36
HUD_PANEL_PADDING = 12
HUD_PANEL_BORDER_WIDTH = 2
HUD_PANEL_FILL_COLOR = (10, 10, 10)
HUD_PANEL_BORDER_COLOR = "white"
HUD_TEXT_COLOR = "white"
HUD_SCORE_PANEL_WIDTH = 420
HUD_SCORE_PANEL_HEIGHT = 54
HUD_SCORE_PANEL_TOP = 10
HUD_STATUS_PANEL_WIDTH = 320
HUD_STATUS_PANEL_MARGIN = 16
HUD_STATUS_ROW_SPACING = 40
HUD_STATUS_LABEL_WIDTH = 170
HUD_LIFE_ICON_RADIUS = 9
HUD_LIFE_ICON_SPACING = 24
HUD_BOMB_ICON_RADIUS = 9
HUD_BOMB_ICON_SPACING = 24
HUD_POWERUP_ICON_RADIUS = 9
HUD_GAME_OVER_MESSAGE = "GAME OVER"
HUD_GAME_OVER_RETRY_MESSAGE = "Press R to Retry"
HUD_GAME_OVER_QUIT_MESSAGE = "Press Q to Quit"
HUD_GAME_OVER_INSTRUCTION_OFFSET = 40
POWERUP_RADIUS = 15
POWERUP_SPAWN_INTERVAL_SECONDS = 18
POWERUP_MAX_ON_SCREEN = 1
POWERUP_LIFETIME_SECONDS = 12
POWERUP_SPAWN_MARGIN = 80
SPEED_BOOST_MULTIPLIER = 1.6
SPEED_BOOST_DURATION_SECONDS = 15.0
SHIELD_DRAW_RADIUS = PLAYER_RADIUS * 1.8
SHIELD_ABSORB_INVULNERABLE_SECONDS = 1.0
PLAYER_STARTING_BOMBS = 3
BOMB_RADIUS = 150
BOMB_EFFECT_DURATION_SECONDS = 0.25
BOMB_BODY_RADIUS = 10

MAX_LEVEL = 25
LEVEL_SCORE_BASE_STEP = 1500
LEVEL_SCORE_STEP_GROWTH = 200
LEVEL_TRANSITION_SECONDS = 2.0
LEVEL_SPAWN_PAUSE_SECONDS = 2.5
LEVEL_SAFE_RADIUS = 180
LEVEL_UP_INVULNERABLE_SECONDS = 2.5

ASTEROID_SPAWN_RATE_LEVEL_1 = 1.6
ASTEROID_SPAWN_RATE_LEVEL_25 = 0.55
ASTEROID_SPEED_MIN_LEVEL_1 = 35
ASTEROID_SPEED_MAX_LEVEL_1 = 75
ASTEROID_SPEED_MIN_LEVEL_25 = 90
ASTEROID_SPEED_MAX_LEVEL_25 = 180
ASTEROID_MAX_COUNT_LEVEL_1 = 4
ASTEROID_MAX_COUNT_LEVEL_25 = 18

LEVEL_SCORE_THRESHOLDS = [0]
for level in range(2, MAX_LEVEL + 1):
    previous = LEVEL_SCORE_THRESHOLDS[-1]
    step = LEVEL_SCORE_BASE_STEP + (level - 2) * LEVEL_SCORE_STEP_GROWTH
    LEVEL_SCORE_THRESHOLDS.append(previous + step)


def level_progress(level: int) -> float:
    if MAX_LEVEL <= 1:
        return 0.0
    return (level - 1) / (MAX_LEVEL - 1)


def asteroid_spawn_rate_for_level(level: int) -> float:
    progress = level_progress(level)
    return ASTEROID_SPAWN_RATE_LEVEL_1 + progress * (
        ASTEROID_SPAWN_RATE_LEVEL_25 - ASTEROID_SPAWN_RATE_LEVEL_1
    )


def asteroid_speed_range_for_level(level: int) -> tuple[int, int]:
    progress = level_progress(level)
    speed_min = round(
        ASTEROID_SPEED_MIN_LEVEL_1
        + progress * (ASTEROID_SPEED_MIN_LEVEL_25 - ASTEROID_SPEED_MIN_LEVEL_1)
    )
    speed_max = round(
        ASTEROID_SPEED_MAX_LEVEL_1
        + progress * (ASTEROID_SPEED_MAX_LEVEL_25 - ASTEROID_SPEED_MAX_LEVEL_1)
    )
    return speed_min, speed_max


def asteroid_max_count_for_level(level: int) -> int:
    progress = level_progress(level)
    return round(
        ASTEROID_MAX_COUNT_LEVEL_1
        + progress * (ASTEROID_MAX_COUNT_LEVEL_25 - ASTEROID_MAX_COUNT_LEVEL_1)
    )
